Master
thefuntasty/LocationManager pull request #6
Opened 2016-09-19 09:51 UTC by TFTmilan

Migrate pod to swift 3

2016-09-19 10:02 UTC, kafejo commented on Pod/Classes/LocationManager.swift
> +    typealias AuthorizationFulfillment = (CLAuthorizationStatus) -> Void
typo, it should be `fulfilment`

2016-09-19 10:08 UTC, kafejo commented on Pod/Classes/LocationManager.swift
> +    open class func removeLocationObserver(_ observer: LocationObserver) {
I would also refactor naming according to Swift 3 naming guidelines. For example this method should be 
```swift
open class func remove(locationObserver: LocationObserver) {
}
```

2016-09-19 10:10 UTC, kafejo commented on Pod/Classes/LocationManager.swift
> +            for fulfillment in askForLocationServicesFulfillments {
Easier to use `forEach`
```swift
askForLocationServicesFulfillments.forEach { $0(status) }
```

2016-09-19 10:13 UTC, kafejo commented on Pod/Classes/LocationRequest.swift
> +            guard let _location = location , self.validateLocation(_location) else {
don't use underscore.

2016-09-19 10:16 UTC, kafejo requested changes
It needs to rename all methods according to Swift 3 naming guidelines.

2016-09-19 10:16 UTC, kafejo commented on Example/LocationManager/ViewController.swift
> +        //}
what's that @TFTmilan ?

2016-09-19 10:44 UTC, jakubknejzlik commented on Pod/Classes/LocationManager.swift
> +
Question: are these spaces based on some swift design, or is it just for readability (subjective)?

2016-09-19 10:47 UTC, mkj-is commented on Pod/Classes/LocationManager.swift
> +    typealias AuthorizationFulfillment = (CLAuthorizationStatus) -> Void
I believe we use US spelling, like all the system frameworks. Therefore it is okay.

2016-09-19 10:47 UTC, jakubknejzlik commented on Pod/Classes/LocationManager.swift
> +                }.min() ?? 0
Wrong padding int  (-1 ... previous version was incorrect too - even in previous `.min()...` call)

2016-09-19 11:01 UTC, mkj-is commented on Pod/Classes/LocationManager.swift
> +    fileprivate var locationRequests: [LocationRequest] = []
The preferred variant of writing these initializations is:

`fileprivate var locationRequests = [LocationRequest]()`

2016-09-19 11:02 UTC, mkj-is commented on Pod/Classes/LocationManager.swift
>              },rejection: reject)
Missing space.

2016-09-19 11:04 UTC, mkj-is commented on Pod/Classes/LocationManager.swift
> +            askWithFulfillment({ (status: CLAuthorizationStatus) -> Void in
Unnecessary parenthesis.

2016-09-19 11:04 UTC, jakubknejzlik requested changes

2016-09-19 11:05 UTC, mkj-is commented on Pod/Classes/LocationManager.swift
> +            }.min() ?? 0
Bad indentation.

2016-09-19 11:05 UTC, jakubknejzlik commented
Do we really want to add Pods in example to the repository?

2016-09-19 11:06 UTC, mkj-is requested changes

2016-09-19 11:06 UTC, mkj-is commented on Example/LocationManager.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = LLW79T3K9U;
We should set automatic code signing in Xcode 8 so the people who want to try this repository have no problems running it.

2016-09-19 11:06 UTC, mkj-is commented on Example/LocationManager/LocationObserverLabel.swift
> +    func didUpdateLocation(_ manager: LocationManager, location: CLLocation) {
Change method name according to Swift 3 coventions.

2016-09-19 11:06 UTC, mkj-is commented on Example/LocationManager/ViewController.swift
> +
I believe the methods are simple enough and we don't need so much space.

2016-09-19 11:06 UTC, mkj-is commented on Example/Pods/Pods.xcodeproj/project.pbxproj
> +// !$*UTF8*$!
The Pod project should not be in the version control.

2016-09-19 11:06 UTC, mkj-is commented on Example/Tests/Tests.swift
> -    func didUpdateLocation(manager: LocationManager, location: CLLocation) {
Change method name according to Swift 3 coventions.

2016-09-19 11:10 UTC, mkj-is commented
We agreed here, that the Pods project is not needed and should be added to .gitignore. Also @TFTmilan, could you rename the pull request to something sane. Like Swift 3 version? Thanks!

2016-09-19 11:10 UTC, crinos9 commented on Example/LocationManager/ViewController.swift
> +        //}
use catch {} instead of removing error

2016-09-19 11:19 UTC, zvonicek commented
![](https://media.giphy.com/media/QT9SVRVexMgOk/giphy.gif)

2016-09-19 11:25 UTC, crinos9 commented on Example/LocationManager/ViewController.swift
> +        }//.error { error in
catch {} is available in promisekit 4.0 instead of error {}

2016-09-20 09:09 UTC, TFTmilan commented on Pod/Classes/LocationManager.swift
> +
just for readability

2016-09-21 10:44 UTC, mkj-is commented on Example/LocationManager/LocationObserverLabel.swift
> +    func didUpdateLocation(_ manager: LocationManager, location: CLLocation) {
@TFTmilan Still not renamed according to Swift 3 guidelines.

2016-09-21 10:45 UTC, mkj-is commented on Example/Tests/Tests.swift
> -    func didUpdateLocation(manager: LocationManager, location: CLLocation) {
Same here.

2016-09-21 10:46 UTC, mkj-is commented on Pod/Classes/LocationManager.swift
> +    open class func askForLocationServicesIfNeeded() -> Promise<CLAuthorizationStatus>{
Missing space before opening brace.

2016-09-21 10:47 UTC, mkj-is commented on Pod/Classes/LocationManager.swift
> +    open func askForLocationServicesIfNeeded() -> Promise<CLAuthorizationStatus>{
Missing space before opening brace.

2016-09-21 10:47 UTC, mkj-is commented on Pod/Classes/LocationManager.swift
> +                if locationManager.responds(to: #selector(CLLocationManager.requestAlwaysAuthorization)){
Missing space before opening brace.

2016-09-21 10:48 UTC, mkj-is commented on Pod/Classes/LocationManager.swift
> +    open func locationManager(_ manager: CLLocationManager, didChangeAuthorization status: CLAuthorizationStatus) {
Rename according to Swift 3 conventions.

2016-09-21 10:48 UTC, mkj-is commented on Pod/Classes/LocationManager.swift
> +    open func locationManager(_ manager: CLLocationManager, didUpdateLocations locations: [CLLocation]) {
Rename according to Swift 3 conventions.

2016-09-21 10:49 UTC, mkj-is commented on Pod/Classes/LocationObserver.swift
> +    func updateLocationFromTimer(_ location: CLLocation) {
Rename according to Swift 3 conventions.

2016-09-21 10:49 UTC, mkj-is requested changes

2016-09-21 18:35 UTC, jakubknejzlik commented on Pod/Classes/LocationRequest.swift
> +            guard let location = location , self.validate(location: location) else {
Remove `self.` from `self.validate`... space before comma should be removed too

2016-09-21 18:36 UTC, jakubknejzlik commented on Pod/Classes/LocationRequest.swift
>          self.locationManager.locationRequestDidTimeout(self)
Remove `self.`

2016-09-21 18:36 UTC, jakubknejzlik commented on Pod/Classes/LocationRequest.swift
>          self.timer = nil
Remove `self.`

2016-09-30 09:11 UTC, jakubknejzlik approved these changes

2016-09-30 09:12 UTC, jakubknejzlik commented
@kafejo are you ok with current state? Should we merge?

2016-09-30 15:07 UTC, kafejo commented
Nope. Still pending changes that @mkj-is pointed out.

2016-09-30 19:19 UTC, jakubknejzlik commented
@TFTmilan could you please check it?

2017-07-09 17:47 UTC, maguro commented on Example/Pods/PromiseKit/Sources/after.swift
> +public func after(interval: TimeInterval) -> Promise<Void> {
Should this maybe have been:

    public func after(seconds: TimeInterval) -> Promise<Void>

and

    public func after(interval: DispatchTimeInterval) -> Promise<Void>

2017-07-09 17:50 UTC, maguro commented on Example/Pods/PromiseKit/Sources/after.swift
> +public func after(interval: TimeInterval) -> Promise<Void> {
Opps, wrong project.  :)

2017-09-05 17:27 UTC, mkj-is approved these changes

2017-09-05 17:29 UTC, mkj-is commented
@TFTmilan Can you please merge? The issues I pointed out are not so critical and just a fine-tuning and we are not using this pod for location management anymore.

(And I see this pull request all the time when I go to the list of pull request where I am mentioned. 💣)

2017-09-05 21:51 UTC, merged